# Generated by Django 5.2 on 2025-04-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='category',
            field=models.CharField(choices=[('developer', 'Developer'), ('designer', 'UI/UX Designer'), ('project_manager', 'Project Manager'), ('qa', 'QA Engineer'), ('devops', 'DevOps Engineer'), ('product', 'Product Manager'), ('marketing', 'Marketing Specialist'), ('support', 'Technical Support'), ('sales', 'Sales Representative')], default='developer', max_length=50),
        ),
    ]
